apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: durga61/cart-service
    newTag: 47c2b52
  - name: durga61/order-service
    newTag: 594fac5
  - name: durga61/product-service
    newTag: 13db18f
