apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart
  namespace: argocd-staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: durga61/cart-service
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/allow-tags: "regexp:^[a-f0-9]{7}$" 
    # This annotation tells Argo CD Image Updater to write back the updated image tag to the Git repository"
    # if required, set 'pull-request'
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/apps-deployment.git'
    targetRevision: main
    path: overlays/staging/cart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
