apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: order=durga61/order-service
    argocd-image-updater.argoproj.io/order.kustomize.image-name: durga61/order-service
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/allow-tags: "regexp:^[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization:../../../base/images
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'https://github.com/durga61/apps-deployment.git'
    targetRevision: main
    path: overlays/staging/order
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    syncOptions:
    # Automatically create the namespace if it does not exist
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
