# ArgoCD Application manifest for deploying the product service to the staging environment.
# This file configures automated image updates, namespace creation, and GitOps deployment from the main branch.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product
  namespace: argocd-staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: durga61/product-service
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/allow-tags: "regexp:^[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'https://github.com/durga61/apps-deployment.git'
    targetRevision: main
    path: overlays/staging/product
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    syncOptions:
    # Automatically create the namespace if it does not exist
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
